name: segmentation_renderer
description: "A collection of painters to help render segmentation maps, which will help you visualize contours or bounding shapes on images."
version: 1.0.2
homepage: https://github.com/abdelaziz-mahdy/segmentation_renderer

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
